### ISSUE TITLE
Is that theoretically possible?

### ISSUE THREAD

**Issue by qingyuan0o0** [luislavena/homelab-headscale#1]
Based on https://fly.io/docs/app-guides/udp-and-tcp/ , I found out if it's udp-enabled, whether or not it's possible to implement UDP/3478 services that open DERP
>[[services]]
>  internal_port = 3478
>  protocol = "udp"
>
>  [[services.ports]]
>    port = "3478"
>
>[[services]]
>  internal_port = 8080
>  protocol = "tcp"
>
>  [[services.ports]]
>    port = "8080"

**Comment by luislavena** [comment]
Hello @qingyuan0o0, thanks for your patience.

It might be possible, according to Fly's documentation and headscale [config file](https://github.com/juanfont/headscale/blob/main/config-example.yaml#L92-L96), you could define the UDP listening interface and port.

I haven't tested, but I believe you will also need to provide your own DERP list for it to work (see [here](https://github.com/juanfont/headscale/blob/main/config-example.yaml#L99-L100) and [here](https://github.com/juanfont/headscale/blob/main/derp-example.yaml))

Cheers.
